AWSTemplateFormatVersion: "2010-09-09"
Description: "Create ECR ofr ECS"

Parameters:
  ECRName:
    Type: String
    Default: monolith
    Description: ECR name

Resources:
  ECR:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Ref ECRName
      ImageScanningConfiguration:
        ScanOnPush: false
      LifecyclePolicy:
        LifecyclePolicyText: |
          {
            "rules": [
              {
                "rulePriority": 1,
                "description": "Keeps only last 2 images",
                "selection": {
                  "tagStatus": "any",
                  "countType": "imageCountMoreThan",
                  "countNumber": 2
                },
                "action": {
                  "type": "expire"
                }
              }
            ]
          }

Outputs:
  RepositoryUri:
    Description: "URI del ECR"
    Value: !GetAtt ECR.RepositoryUri
  RepositoryName:
    Description: "Nombre del ECR"
    Value: !Ref ECR
